FROM ubuntu:22.04

LABEL maintainer="alantrbt" \
      description="Docker image for SRA Toolkit"

# Installer les dépendances de base
RUN apt-get update && apt-get install -y wget tar gzip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

# Télécharger et installer le SRA Toolkit
RUN wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-ubuntu64.tar.gz && \
    tar -xzf sratoolkit.current-ubuntu64.tar.gz && \
    SRADIR=$(tar -tzf sratoolkit.current-ubuntu64.tar.gz | head -1 | cut -f1 -d"/") && \
    mv "$SRADIR" sratoolkit && \
    ln -s /opt/sratoolkit/bin/* /usr/local/bin/ && \
    rm sratoolkit.current-ubuntu64.tar.gz

# Répertoire de travail par défaut
WORKDIR /data

# Commande par défaut
CMD ["bash"]
