# =========================================================
#  SRA Toolkit (fasterq-dump) - Reproducible container
# =========================================================
FROM ubuntu:22.04

LABEL maintainer="Alan <alan@example.com>"
LABEL description="Container for SRA Toolkit (fasterq-dump) used in RNA-seq pipeline"

# Evite les questions interactives
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget curl gzip tar ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Download and install SRA Toolkit (official binary)
RUN wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-ubuntu>
    tar -xzf /tmp/sratoolkit.tar.gz -C /opt && \
    mv /opt/sratoolkit.* /opt/sratoolkit && \
    ln -s /opt/sratoolkit/bin/* /usr/local/bin/ && \
    rm /tmp/sratoolkit.tar.gz

# Test binaries (during build)
RUN fasterq-dump --version

# Working directory
WORKDIR /data

ENTRYPOINT ["/bin/bash"]
