FROM ubuntu:22.04

# Met à jour le système et installe les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    wget \
    ca-certificates \
    libncurses5 \
    libncursesw5 \
    libbz2-1.0 \
    liblzma5 \
    libcurl4-openssl-dev \
    libssl-dev \
    gcc \
    make \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Télécharge et installe SRA Toolkit
RUN wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-ubuntu64.tar.gz && \
    tar -xzf sratoolkit.current-ubuntu64.tar.gz && \
    mv sratoolkit.*-ubuntu64 /usr/local/sratoolkit && \
    rm sratoolkit.current-ubuntu64.tar.gz

ENV PATH="/usr/local/sratoolkit/bin:${PATH}"

ENTRYPOINT ["/bin/bash"]
